debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    jpa기술 사용할 때 쿼리로그를 디버그 로그를 확인 할수 있는데 바인딩 파라미터가 물음표로 보이는데 그것 을 관찰하기 위함
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: prominju
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8 버전에 맞게 쓸수 있는 이름
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # 테스트용 데이버테이스를 만들어준다
    hibernate:
      ddl-auto: create # entity만 보고도 create table을 해줌
    show-sql: true # sql 쿼리 보여줌
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always # data.sql 언제 작동시킬건지 해줌
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
server:
  port: 8081
---
# yaml 파일은 줄 3개를 기준으로 새로운 도큐먼트를 만들수 있다
#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none